name 'oci_caas_bastion'
maintainer 'Jon DeCamp (OCI CaaS)'
maintainer_email 'jon.dcamp@oracle.com'
license 'Universal Permissive License v1.0'
description 'Installs/Configures oci_caas_bastion'
version '0.4.2'
chef_version '>= 16.0'

depends 'oci_caas_base'
depends 'firewalld'
depends 'selinux_policy'
depends 'wazuh_agent'

issues_url 'https://github.com/oracle-quickstart/oci-caas-bastion/issues'
source_url 'https://github.com/oracle-quickstart/oci-caas-bastion'